### ISSUE TITLE
BLAS interface completeness?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLinearAlgebra/MKL.jl#138] opened 2023-11-10 11:29 UTC
I was pretty surprised to find that the MKL.jl bindings were incomplete. That doesn't seem to be documented anywhere? In order for `using MKL` to be non-breaking, it needs to be complete or have fallbacks in any case where MKL does not provide a solution. In terms of what I can find from https://discourse.julialang.org/t/again-errors-with-no-blas-lapack-library-loaded/105943/8 https://github.com/SciML/LinearSolve.jl/issues/427, at least `lacpy` seems to be missing.

**Comment by imciner2** [comment] 2023-11-10 11:39
I'm a bit confused, what do you mean by the bindings being incomplete and the function being missing? This should be handled by the lbt layer redirecting to MKL's function, and the stacktrace given in https://github.com/SciML/LinearSolve.jl/issues/427#issuecomment-1805550159 seems to show it is actually being dispatched into the library for the `lacpy` call.

**Comment by andreasvarga** [comment] 2023-11-10 11:40
See also [here](https://discourse.julialang.org/t/wrapping-lapack-functions-using-mkl/105997/4).

**Comment by andreasvarga** [comment] 2023-11-10 12:38
From my tests, it appears that the two pairs of LAPACK auxiliary routines `dlanv2/slanv2` and `dladiv/sladiv` are missing in MKL.

**Comment by andreasnoack** [comment] 2023-11-10 14:03
The symbol is called from inside of the SLICOT library. Will the mapping also apply to such calls?

**Comment by imciner2** [comment] 2023-11-10 14:48
Is slicot linked against libblastrampoline? If so, I believe this mapping would also apply to calls that are made from SLICOT through libblastrampoline.

**Comment by andreasvarga** [comment] 2023-11-10 16:35
What are the implications on the `ccall()` interface? In the moment, I am using `:dlanv2_`, which works for OpenBLAS but not for MKL. (see [example](https://discourse.julialang.org/t/wrapping-lapack-functions-using-mkl/105997/4).). Should I use another symbol for MKL?

**Comment by andreasnoack** [comment] 2023-11-10 16:55
> Is slicot linked against libblastrampoline?

Looks like it https://github.com/JuliaPackaging/Yggdrasil/blob/c0b6369e57c315ea92ec01c3734d2a0ccb559a5d/S/SLICOT/build_tarballs.jl#L84

**Comment by andreasvarga** [comment] 2023-11-10 17:01
There should be no problems with SLICOT. I contacted the main developer of SLICOT (Vasile Sima) and he confirmed that SLICOT is MKL compliant (of course there could be differences in the employed versions). I myself replaced the function dlanv2 with a generic version programmed in Julia and all tests for PeriodicSystems are passed also with MKL. So until now, only dlanv2 and dladiv raise problems.

**Comment by imciner2** [comment] 2023-11-10 17:19
That mapping will also fix the ccall for the functions.

I have put together an initial list of methods that seem to be missing and need this mapping in https://github.com/JuliaLinearAlgebra/MKL.jl/pull/140. I tried your example from the forum with that change in the package, and it works calling `dlanv2` with the change.

**Comment by ViralBShah** [comment] 2024-02-23 19:57
Fixed in #140 and should be further fixed in a future MKL release upstream as well.

**Closed by ViralBShah** 2024-02-23 19:57 UTC
